version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run: echo "Building the Docker image..."
      - run: docker build -t rizqonmaulana/my-node-app .
      - run: echo "Build completed!"
      - run: echo "Logging into Docker Hub..."
      - run: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: echo "Pushing image to Docker Hub..."
      - run: docker push rizqonmaulana/my-node-app
      - run: echo "Push completed!"

  deploy:
    machine:
      image: ubuntu-2204:current
    steps:
      - add_ssh_keys:
          fingerprints:
            - "your-ssh-key-fingerprint"  # ✅ Add SSH key for VPS access
      - run: echo "Deploying to VPS..."
      - run: ssh ubuntu@your-vps-ip "docker pull rizqonmaulana/my-node-app && docker service update --image rizqonmaulana/my-node-app my-service"
      - run: echo "Deployment completed!"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
