version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - setup_remote_docker
      - run: echo "Building the app..."
      - run: docker build -t rizqonmaulana/my-node-app .
      - run: echo "Build completed!"

  push:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - setup_remote_docker
      - run: echo "Logging in to Docker Hub..."
      - run: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: docker tag my-node-app rizqonmaulana/my-node-app
      - run: docker push rizqonmaulana/my-node-app
      - run: echo "Push completed!"

  deploy:
    docker:
      - image: node:18
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "your-ssh-key-fingerprint"
      - run:
          name: Deploy to Docker Swarm
          command: ssh your-user@your-vps-ip 'docker service update --force my-app_app'

workflows:
  version: 2
  build_push_deploy:
    jobs:
      - build
      - push:
          requires:
            - build
      - deploy:
          requires:
            - push
