version: 2.1

jobs:
  build:
    docker:
      - image: node:18
    steps:
      - checkout
      - run: echo "Building the app..."
      - run: docker build -t your-dockerhub-username/my-node-app .
      - run: echo "Build completed!"

  push:
    docker:
      - image: node:18
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run: echo "Logging in to Docker Hub..."
      - run: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: docker tag my-node-app your-dockerhub-username/my-node-app
      - run: docker push your-dockerhub-username/my-node-app
      - run: echo "Push completed!"

  deploy:
    docker:
      - image: node:18
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "your-ssh-key-fingerprint"
      - run:
          name: Deploy to Docker Swarm
          command: ssh your-user@your-vps-ip 'docker service update --force my-app_app'

workflows:
  version: 2
  build_push_deploy:
    jobs:
      - build
      - push:
          requires:
            - build
      - deploy:
          requires:
            - push
